#person:
#  last-name: 五指山
#  sex: 男
#  age: 20
#  birth: 2000/01/01
#  map:
#    property: v1
#    form: v2
#  list:
#    - list1
#    - list2
#  Cattle:
#    name: 老黄牛
#    age: 5

  
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/issue?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    mode: HTML
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true